# Generated by Django 4.2.7 on 2025-10-19 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(default='', max_length=120)),
                ('government_id', models.CharField(blank=True, help_text='Government ID number (e.g., National ID or Passport)', max_length=20, null=True)),
                ('id_document', models.ImageField(blank=True, null=True, upload_to='id_documents/')),
                ('landlord_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('user_type', models.CharField(choices=[('landlord', 'Landlord'), ('tenant', 'Tenant')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('mpesa_till_number', models.CharField(blank=True, help_text='M-Pesa till number for direct payments (landlords only)', max_length=20, null=True)),
                ('phone_number', models.CharField(blank=True, help_text='User phone number in international format', max_length=30, null=True)),
                ('emergency_contact', models.CharField(blank=True, help_text='Emergency contact phone number', max_length=30, null=True)),
                ('reminder_mode', models.CharField(choices=[('days_before', 'Days Before Due Date'), ('fixed_day', 'Fixed Day of Month')], default='days_before', help_text='How the tenant wants to receive rent reminders', max_length=20)),
                ('reminder_value', models.IntegerField(default=10, help_text="For 'days_before': days before due date; For 'fixed_day': day of the month (1-31)")),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('unit_count', models.IntegerField()),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UnitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('number_of_units', models.IntegerField(default=0, help_text='Number of units of this type to create automatically')),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_types', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_code', models.CharField(default='', max_length=30, unique=True)),
                ('unit_number', models.CharField(max_length=10)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('bedrooms', models.IntegerField(default=0)),
                ('bathrooms', models.IntegerField(default=0)),
                ('rent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rent_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rent_remaining', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rent_due_date', models.DateField(blank=True, null=True)),
                ('deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
                ('assigned_date', models.DateTimeField(blank=True, null=True)),
                ('left_date', models.DateTimeField(blank=True, null=True)),
                ('property_obj', models.ForeignKey(db_column='property_id', on_delete=django.db.models.deletion.CASCADE, related_name='unit_list', to='accounts.property')),
                ('tenant', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('unit_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.unittype')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('free', 'Free (60-day trial)'), ('starter', 'Starter (up to 10 units)'), ('basic', 'Basic (10-50 units)'), ('professional', 'Professional (50-100 units)'), ('onetime', 'One-time (Unlimited properties)')], default='free', max_length=20)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
