# Generated by Django 4.2.7 on 2025-10-04 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mpesa_till_number',
            field=models.CharField(blank=True, help_text='M-Pesa till number for direct payments (landlords only)', max_length=20, null=True),
        ),
    ]
