# Generated by Django 4.2.7 on 2025-09-30 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20250929_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('free', 'Free (60-day trial)'), ('basic', 'Basic'), ('medium', 'Medium'), ('premium', 'Premium'), ('onetime', 'One-time Payment')], default='free', max_length=20),
        ),
    ]
