# Generated by Django 4.2.7 on 2025-10-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_mpesa_till_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='emergency_contact',
            field=models.CharField(blank=True, help_text='Emergency contact phone number', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, help_text='User phone number in international format', max_length=30, null=True),
        ),
    ]
