# Generated by Django 4.2.7 on 2025-10-09 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='government_id',
            field=models.CharField(blank=True, help_text='Government ID number (e.g., National ID or Passport)', max_length=20, null=True),
        ),
    ]
