# Generated by Django 4.2.7 on 2025-10-10 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_government_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reminder_mode',
            field=models.CharField(choices=[('days_before', 'Days Before Due Date'), ('fixed_day', 'Fixed Day of Month')], default='days_before', help_text='How the tenant wants to receive rent reminders', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='reminder_value',
            field=models.IntegerField(default=10, help_text="For 'days_before': days before due date; For 'fixed_day': day of the month (1-31)"),
        ),
    ]
