# Generated by Django 4.2.7 on 2025-10-10 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_reminder_mode_customuser_reminder_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='unittype',
            name='number_of_units',
            field=models.IntegerField(default=0, help_text='Number of units of this type to create automatically'),
        ),
    ]
