version: '3.8'

services:
  web:
    build: .
    container_name: makau_rentals
    working_dir: /app
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000 --reload
    volumes:
      - ./app:/app
      - static_volume:/app/static
      - media_volume:/app/media
    expose:
      - "8000"
    env_file:
      - ./app/app/.env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: makau_postgres
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - ./app/app/.env
    ports:
      - "5432:5432"

  nginx:
    build:
      context: .
      dockerfile: ./nginx/nginx.dockerfile
    container_name: nginx_proxy
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6379:6379"
    restart: always

volumes:
  db_data:
  static_volume:
  media_volume:
