# Generated by Django 4.2.7 on 2025-10-19 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_category', models.CharField(choices=[('electrical', 'Electrical'), ('plumbing', 'Plumbing'), ('noise', 'Noise'), ('safety', 'Safety/Violence'), ('wifi', 'WiFi'), ('maintenance', 'General Maintenance'), ('pest', 'Pest Control'), ('security', 'Security'), ('cleanliness', 'Cleanliness'), ('other', 'Other')], max_length=20)),
                ('priority_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('issue_title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=15)),
                ('reported_date', models.DateTimeField(auto_now_add=True)),
                ('resolved_date', models.DateTimeField(blank=True, null=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='report_attachments/')),
                ('assigned_to', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'landlord'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reports', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(limit_choices_to={'user_type': 'tenant'}, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='accounts.unit')),
            ],
            options={
                'verbose_name': 'Maintenance Report',
                'verbose_name_plural': 'Maintenance Reports',
                'ordering': ['-reported_date'],
            },
        ),
    ]
