# Generated by Django 4.2.7 on 2025-10-19 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mpesa_receipt_number', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('mpesa_checkout_request_id', models.CharField(blank=True, help_text='M-Pesa checkout request ID for tracking STK push', max_length=100, null=True)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('subscription_type', models.CharField(choices=[('free', 'Free (60-day trial)'), ('starter', 'Starter (up to 10 units)'), ('basic', 'Basic (10-50 units)'), ('professional', 'Professional (50-100 units)'), ('onetime', 'One-time (Unlimited properties)')], max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Success', 'Success'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_type', models.CharField(choices=[('rent', 'Rent'), ('deposit', 'Deposit'), ('maintenance', 'Maintenance'), ('other', 'Other')], default='rent', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('mpesa_receipt', models.CharField(blank=True, max_length=50, null=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('payment_method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('cash', 'Cash'), ('bank', 'Bank Transfer')], default='mpesa', max_length=20)),
                ('mpesa_checkout_request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(limit_choices_to={'user_type': 'tenant'}, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.unit')),
            ],
        ),
        migrations.AddConstraint(
            model_name='subscriptionpayment',
            constraint=models.UniqueConstraint(condition=models.Q(('mpesa_receipt_number', ''), _negated=True), fields=('mpesa_receipt_number',), name='unique_mpesa_receipt'),
        ),
    ]
