# Generated by Django 4.2.7 on 2025-09-29 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
    ]
