# Generated by Django 4.2.7 on 2025-10-09 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0002_payment_payment_type_alter_payment_tenant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='subscription_type',
            field=models.CharField(choices=[('free', 'Free (60-day trial)'), ('starter', 'Starter (up to 10 units)'), ('basic', 'Basic (10-50 units)'), ('professional', 'Professional (50-100 units)'), ('onetime', 'One-time (Unlimited properties)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='user',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'landlord'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription_payments', to=settings.AUTH_USER_MODEL),
        ),
    ]
