# Generated by Django 4.2.7 on 2025-10-09 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_government_id'),
        ('payments', '0003_alter_subscriptionpayment_subscription_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='unit_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.unittype'),
        ),
    ]
