# Generated by Django 4.2.7 on 2025-10-10 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_payment_tenant'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE payments_subscriptionpayment DROP CONSTRAINT IF EXISTS payments_subscriptionpayment_mpesa_receipt_number_key;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
