# Generated by Django 4.2.7 on 2025-10-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_remove_unique_mpesa_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='mpesa_receipt_number',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
